import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        activa: {
          amber: 'rgb(var(--color-activa-amber) / <alpha-value>)',
          'amber-hover': 'rgb(var(--color-activa-amber-hover) / <alpha-value>)',
          teal: 'rgb(var(--color-activa-teal) / <alpha-value>)',
          'teal-hover': 'rgb(var(--color-activa-teal-hover) / <alpha-value>)',
          'teal-soft': 'rgb(var(--color-activa-teal-soft) / <alpha-value>)',
          graphite: 'rgb(var(--color-activa-graphite) / <alpha-value>)',
          'graphite-secondary': 'rgb(var(--color-activa-graphite-secondary) / <alpha-value>)',
          'graphite-medium': 'rgb(var(--color-activa-graphite-medium) / <alpha-value>)',
          'warm-white': 'rgb(var(--color-activa-warm-white) / <alpha-value>)',
          mist: 'rgb(var(--color-activa-mist) / <alpha-value>)',
        },
        'background-page': 'rgb(var(--color-background-page) / <alpha-value>)',
        'background-surface': 'rgb(var(--color-background-surface) / <alpha-value>)',
        'background-surface-muted': 'rgb(var(--color-background-surface-muted) / <alpha-value>)',
        'background-inverse': 'rgb(var(--color-background-inverse) / <alpha-value>)',
        'text-primary': 'rgb(var(--color-text-primary) / <alpha-value>)',
        'text-secondary': 'rgb(var(--color-text-secondary) / <alpha-value>)',
        'text-inverse': 'rgb(var(--color-text-inverse) / <alpha-value>)',
        'text-link': 'rgb(var(--color-text-link) / <alpha-value>)',
        'text-disabled': 'rgb(var(--color-text-disabled) / <alpha-value>)',
        'action-primary': 'rgb(var(--color-action-primary) / <alpha-value>)',
        'action-primary-hover': 'rgb(var(--color-action-primary-hover) / <alpha-value>)',
        'action-primary-text': 'rgb(var(--color-action-primary-text) / <alpha-value>)',
        'action-secondary': 'rgb(var(--color-action-secondary) / <alpha-value>)',
        'action-secondary-hover': 'rgb(var(--color-action-secondary-hover) / <alpha-value>)',
        'action-secondary-text': 'rgb(var(--color-action-secondary-text) / <alpha-value>)',
        'border-default': 'rgb(var(--color-border-default) / <alpha-value>)',
        'border-strong': 'rgb(var(--color-border-strong) / <alpha-value>)',
        'border-focus': 'rgb(var(--color-border-focus) / <alpha-value>)',
        'status-success': 'rgb(var(--color-status-success) / <alpha-value>)',
        'status-information': 'rgb(var(--color-status-information) / <alpha-value>)',
        'status-warning': 'rgb(var(--color-status-warning) / <alpha-value>)',
        'status-error': 'rgb(var(--color-status-error) / <alpha-value>)',
        'status-disabled': 'rgb(var(--color-status-disabled) / <alpha-value>)',
        // Legacy Sortealo blue; retained until existing references are migrated.
        brand: { DEFAULT: '#3b82f6', dark: '#2563eb', light: '#eff6ff' },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        display: ['var(--font-sora)', 'var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      spacing: {
        'activa-0': 'var(--spacing-0)',
        'activa-4': 'var(--spacing-4)',
        'activa-8': 'var(--spacing-8)',
        'activa-12': 'var(--spacing-12)',
        'activa-16': 'var(--spacing-16)',
        'activa-20': 'var(--spacing-20)',
        'activa-24': 'var(--spacing-24)',
        'activa-32': 'var(--spacing-32)',
        'activa-40': 'var(--spacing-40)',
        'activa-48': 'var(--spacing-48)',
        'activa-64': 'var(--spacing-64)',
        'activa-80': 'var(--spacing-80)',
        'activa-96': 'var(--spacing-96)',
      },
      borderRadius: {
        'activa-xs': 'var(--radius-xs)',
        'activa-sm': 'var(--radius-sm)',
        'activa-md': 'var(--radius-md)',
        'activa-lg': 'var(--radius-lg)',
        'activa-xl': 'var(--radius-xl)',
        'activa-full': 'var(--radius-full)',
      },
      boxShadow: {
        'activa-xs': 'var(--shadow-xs)',
        'activa-sm': 'var(--shadow-sm)',
        'activa-md': 'var(--shadow-md)',
        'activa-lg': 'var(--shadow-lg)',
      },
      transitionDuration: {
        fast: 'var(--motion-fast)',
        base: 'var(--motion-base)',
        slow: 'var(--motion-slow)',
      },
      transitionTimingFunction: {
        activa: 'var(--motion-easing)',
      },
      zIndex: {
        base: 'var(--layer-base)',
        content: 'var(--layer-content)',
        sticky: 'var(--layer-sticky)',
        dropdown: 'var(--layer-dropdown)',
        overlay: 'var(--layer-overlay)',
        modal: 'var(--layer-modal)',
        toast: 'var(--layer-toast)',
        critical: 'var(--layer-critical)',
      },
    },
  },
  plugins: [],
};
export default config;
